-- MySQL Script generated by MySQL Workbench
-- Mon Jun 24 20:52:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema banco_prova01
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_prova01
-- -----------------------------------------------------
CREATE database`banco_prova01` DEFAULT CHARACTER SET latin1 ;
USE `banco_prova01` ;

-- -----------------------------------------------------
-- Table `banco_prova01`.`cliente`
-- -----------------------------------------------------
CREATE TABLE `cliente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `nacimento` DATE NOT NULL,
  `sexo` VARCHAR(15) NOT NULL,
  `cpf` CHAR(14) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `banco_prova01`.`tipoempresa`
-- -----------------------------------------------------
CREATE TABLE `tipoempresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_empresa` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

	INSERT INTO tipoempresa (id, tipo_empresa) VALUES
    (NULL, 'Academia' ),
    (NULL, 'Clinica');

-- -----------------------------------------------------
-- Table `banco_prova01`.`empresa`
-- -----------------------------------------------------
CREATE TABLE `empresa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `cnpj` VARCHAR(20) NOT NULL,
  `tipoempresa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`tipoempresa_id`)
    REFERENCES `banco_prova01`.`tipoempresa` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

	INSERT INTO `empresa` (`id`,`nome`, `cnpj`, `tipoempresa_id`) VALUES
(NULL, 'arenito fantasia', '00.000.000/0000-00', 1);
-- -----------------------------------------------------
-- Table `banco_prova01`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE `funcionario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `funcao` VARCHAR(50) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `ativo` enum('S','N') NOT NULL,
  `empresa_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`empresa_id`)
    REFERENCES `banco_prova01`.`empresa` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

	INSERT INTO `funcionario` (`id`,`nome`,`funcao`, `email`, `login`,`senha`,`empresa_id`) VALUES
(NULL, 'robson', 'personal','rojv@gmail.com','rppp','1234', 1);
-- -----------------------------------------------------
-- Table `banco_prova01`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE `avaliacao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `peso` FLOAT NOT NULL,
  `altura` FLOAT NOT NULL,
  `imc` FLOAT NOT NULL,
  `data` DATETIME NOT NULL,
  `classificacao` VARCHAR(50) NOT NULL,
  `cliente_id` INT(11) NOT NULL,
  `funcionario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`cliente_id`)
    REFERENCES `banco_prova01`.`cliente` (`id`),
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `banco_prova01`.`funcionario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;